simulation:
  duration: 120
  numPods: 6
  gpuMaxCapacityPerPod: 125
  numWorkers: 600
  processingDelay: 750ms
  simulationMode: "traffic" # Options: "traffic" (new camera traffic model) or "load" (old load generator)
  loadConfigName: "sine_default" # Only used when simulationMode is "load"

# New camera traffic configuration
cameraTraffic:
  totalCameras: 250
  numGroups: 10
  minRate: 0.1
  maxRate: 2.5
  dynamicMultiplier: true # Set to false for constant rate
  periodSec: 90        # Only relevant if dynamicMultiplier is true
  exemptGroup: 5         # Set to a group index (0-9) to exempt, or -1 for no exempt group